/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/buscar/{cep}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca o endereço pelo CEP
         * @description Consulta o ViaCEP. Se ele estiver fora do ar ou lento, usa a BrasilAPI. CEP que não existe devolve 404.
         */
        get: operations["GetAddressByZipCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/lote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Busca vários CEPs de uma vez
         * @description Recebe de 1 a 20 CEPs e devolve um item para cada um, na mesma ordem, com o status encontrado, nao_encontrado ou invalido. Usa o mesmo cache e o mesmo fallback da busca por CEP.
         */
        post: operations["GetAddressesByZipCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/{cep}/consenso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compara o CEP no ViaCEP e na BrasilAPI
         * @description Consulta as duas fontes ao mesmo tempo, sem cache, e diz se concordam. Compara logradouro, bairro, localidade e UF, sem diferença de acentos e maiúsculas. Quando uma fonte acha o CEP e a outra não, a divergência é "encontrado".
         */
        get: operations["CompareZipCodeSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/{uf}/{cidade}/{logradouro}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca endereços pelo logradouro
         * @description Consulta o ViaCEP, que devolve até 50 endereços. Sem resultado, tenta variações do nome: abreviação por extenso (Av. vira Avenida), número romano ou arábico (XV e 15) e o nome sem o tipo (Rua). Quando uma variação encontra, o cabeçalho X-Logradouro-Buscado diz qual foi, com o texto codificado para URL. Sem nenhum resultado, devolve uma lista vazia.
         */
        get: operations["SearchAddressesByStreet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/cidades/{uf}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as cidades de um estado
         * @description Consulta o IBGE. Estado que não está entre as 27 siglas devolve 400.
         */
        get: operations["GetCitiesByState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/{cep}/coordenadas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coordenadas do CEP
         * @description Latitude e longitude do CEP, vindas da BrasilAPI. São aproximadas: na maioria dos CEPs, apontam para o centro da cidade, não para a rua. CEP sem coordenadas devolve 404.
         */
        get: operations["GetCoordinatesByZipCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distancia/{origem}/{destino}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Distância entre dois CEPs
         * @description Distância em linha reta, em quilômetros, entre as coordenadas dos dois CEPs (fórmula de haversine). Como as coordenadas costumam ser o centro da cidade, serve para distância entre cidades, não dentro da mesma cidade. Não é a distância de carro. Se um dos CEPs não tiver coordenadas, devolve 404 dizendo qual.
         */
        get: operations["GetDistanceBetweenZipCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disponibilidade das fontes
         * @description Histórico das verificações do ViaCEP, da BrasilAPI e do IBGE, feitas a cada 5 minutos e guardadas em memória por até 24 horas. O servidor dorme quando fica sem uso, e o histórico recomeça quando ele acorda: o campo desde diz a partir de quando há dados. Disponibilidade é a porcentagem de verificações saudáveis.
         */
        get: operations["GetSourcesStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressResponse: {
            cep: null | string;
            logradouro: null | string;
            complemento: null | string;
            unidade: null | string;
            bairro: null | string;
            localidade: null | string;
            uf: null | string;
            estado: null | string;
            regiao: null | string;
            tipoLogradouro: null | string;
            nomeLogradouro: null | string;
            enderecoFormatado: string;
        };
        BatchItem: {
            cep: string;
            status: string;
            endereco: null | components["schemas"]["AddressResponse"];
        };
        BatchRequest: {
            /** @description De 1 a 20 CEPs, com ou sem traço. */
            ceps: string[];
        };
        CityResponse: {
            nome: null | string;
        };
        ConsensusResponse: {
            cep: string;
            concordam: boolean;
            divergencias: string[];
            fontes: components["schemas"]["SourceResult"][];
        };
        CoordinatesResponse: {
            cep: string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            fonte: string;
        };
        DistanceResponse: {
            origem: components["schemas"]["CoordinatesResponse"];
            destino: components["schemas"]["CoordinatesResponse"];
            /** Format: double */
            distanciaKm: number | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        SampleResponse: {
            /** Format: date-time */
            em: string;
            status: string;
            /** Format: int32 */
            ms: number | string;
        };
        SourceResult: {
            fonte: string;
            status: string;
            endereco: null | components["schemas"]["AddressResponse"];
        };
        SourceStatusResponse: {
            fonte: string;
            /** Format: double */
            disponibilidade: number | string;
            /** Format: int32 */
            latenciaMediaMs: number | string;
            ultimoStatus: string;
            amostras: components["schemas"]["SampleResponse"][];
        };
        StatusResponse: {
            /** Format: date-time */
            desde: string;
            /** Format: int32 */
            intervaloMinutos: number | string;
            fontes: components["schemas"]["SourceStatusResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAddressByZipCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CEP com 8 dígitos, com ou sem traço. Exemplo: 01001000. */
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAddressesByZipCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CompareZipCodeSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CEP com 8 dígitos, com ou sem traço. Exemplo: 01001000. */
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsensusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchAddressesByStreet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sigla do estado. Exemplo: SP. */
                uf: string;
                /** @description Nome da cidade, com pelo menos 3 caracteres. Exemplo: São Paulo. */
                cidade: string;
                /** @description Parte do nome da rua, com pelo menos 3 caracteres. Exemplo: Paulista. */
                logradouro: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetCitiesByState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sigla do estado. Exemplo: SC. */
                uf: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetCoordinatesByZipCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CEP com 8 dígitos, com ou sem traço. Exemplo: 01001000. */
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinatesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetDistanceBetweenZipCodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CEP de origem. Exemplo: 01001000. */
                origem: string;
                /** @description CEP de destino. Exemplo: 20040020. */
                destino: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistanceResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSourcesStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
}
