/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/buscar/{cep}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca o endereço pelo CEP
         * @description Consulta o ViaCEP. Se ele estiver fora do ar ou lento, usa a BrasilAPI. CEP que não existe devolve 404.
         */
        get: operations["GetAddressByZipCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/{uf}/{cidade}/{logradouro}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca endereços pelo logradouro
         * @description Consulta o ViaCEP, que devolve até 50 endereços. Sem resultado, devolve uma lista vazia.
         */
        get: operations["SearchAddressesByStreet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buscar/cidades/{uf}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as cidades de um estado
         * @description Consulta o IBGE. Estado que não está entre as 27 siglas devolve 400.
         */
        get: operations["GetCitiesByState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressResponse: {
            cep: null | string;
            logradouro: null | string;
            complemento: null | string;
            unidade: null | string;
            bairro: null | string;
            localidade: null | string;
            uf: null | string;
            estado: null | string;
            regiao: null | string;
            tipoLogradouro: null | string;
            nomeLogradouro: null | string;
            enderecoFormatado: string;
        };
        CityResponse: {
            nome: null | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAddressByZipCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CEP com 8 dígitos, com ou sem traço. Exemplo: 01001000. */
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchAddressesByStreet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sigla do estado. Exemplo: SP. */
                uf: string;
                /** @description Nome da cidade, com pelo menos 3 caracteres. Exemplo: São Paulo. */
                cidade: string;
                /** @description Parte do nome da rua, com pelo menos 3 caracteres. Exemplo: Paulista. */
                logradouro: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetCitiesByState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sigla do estado. Exemplo: SC. */
                uf: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
